# Generated by Django 3.1.7 on 2021-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image',
            field=models.ImageField(default='default_title', upload_to='item_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
