# Generated by Django 3.1.7 on 2021-02-22 08:58

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210221_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='image',
            field=models.ImageField(upload_to='item_images', validators=[apis.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
